Profile_location:
    pattern:  /location
    defaults: { _controller: HarvestCloudMarketPlaceProfileBundle:Location:index }

Profile_homepage:
    pattern:  /
    defaults: { _controller: HarvestCloudMarketPlaceProfileBundle:Default:index }
