parameters:
#    harvest_cloud_market_place_hub.example.class: HarvestCloud\MarketPlace\HubBundle\Example

services:
#    harvest_cloud_market_place_hub.example:
#        class: %harvest_cloud_market_place_hub.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
