parameters:
#    harvest_cloud_market_place_seller.example.class: HarvestCloud\MarketPlace\SellerBundle\Example

services:
#    harvest_cloud_market_place_seller.example:
#        class: %harvest_cloud_market_place_seller.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
